# 00. Fundaments de PyTorch

## Que es PyTorch?

[PyTorch](https://pytorch.org/) es un open source machine learning y deep learning framework.

## Para que se usa?

PyTorch le permite manipular y procesar datos y escribir algoritmos de aprendizaje automático utilizando código Python.

## Quien usa PyTorch?

Muchas de las empresas tecnológicas más importantes del mundo, como [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/ ), Tesla y Microsoft, así como empresas de investigación de inteligencia artificial como [OpenAI use PyTorch](https://openai.com/blog/openai-pytorch/) para impulsar la investigación y llevar el aprendizaje automático a sus productos.

![pytorch being used across industry and research](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png)


## Why use PyTorch?

A los investigadores de aprendizaje automático les encanta usar PyTorch. Y a partir de febrero de 2022, PyTorch es el [marco de aprendizaje profundo más utilizado en Papers With Code] (https://paperswithcode.com/trends), un sitio web para rastrear trabajos de investigación de aprendizaje automático y los repositorios de código adjuntos.

PyTorch también ayuda a encargarse de muchas cosas, como la aceleración de GPU (haciendo que su código se ejecute más rápido) detrás de escena.

Así que puedes concentrarte en manipular datos y escribir algoritmos y PyTorch se asegurará de que funcione rápido.

Y si empresas como Tesla y Meta (Facebook) lo utilizan para crear modelos que implementan para impulsar cientos de aplicaciones, conducir miles de automóviles y entregar contenido a miles de millones de personas, también es claramente capaz en el frente del desarrollo.

## Lo que vamos a cubrir en este módulo


| **Topic** | **Contents** |
| ----- | ----- |
| **Introduction to tensors** | Los tensores son el componente básico de todo el machine learning y deep learning. |
| **Creating tensors** | Los tensores pueden representar casi cualquier tipo de datos (imágenes, palabras, tablas de números). |
| **Getting information from tensors** | Si puede poner información en un tensor, querrá sacarla también. |
| **Manipulating tensors** | Machine learning algorithms (como las neural networks) implican manipular tensores de muchas maneras diferentes, como sumar, multiplicar y combinar. |
| **Dealing with tensor shapes** | Uno de los problemas más comunes en el deep learning es lidiar con los desajustes de formas (intentar mezclar tensores de formas incorrectas con otros tensores). |
| **Indexing on tensors** | Si ha indexado una lista de Python o una matriz NumPy, es muy similar con los tensores, excepto que pueden tener muchas más dimensiones. |
| **Mixing PyTorch tensors and NumPy** | PyTorch utiliza tensores ([`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)), NumPy utiliza arrays ([`np.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)) a veces querrás mezclarlos y combinarlos. |
| **Reproducibility** | El Machine learning es muy experimental y, dado que utiliza mucha *aleatoriedad* para funcionar, a veces querrá que esa *aleatoriedad* no sea tan aleatoria. |
| **Running tensors on GPU** | GPUs (Graphics Processing Units) hacen que tu código sea veloz, PyTorch facilita la ejecución de su código en GPU. |


In [1]:
import torch
torch.__version__

'2.0.1+cu118'

## Introduction to tensors

Ahora que hemos importado PyTorch, es hora de aprender sobre los tensores.

Los tensores son el componente fundamental del aprendizaje automático.
Su trabajo es representar datos de forma numérica.

Por ejemplo, podría representar una imagen como un tensor con forma `[3, 224, 224]` que significaría `[color_canales, alto, ancho]`, ya que la imagen tiene `3` canales de color (rojo, verde, azul), una altura de `224` píxeles y un ancho de `224` píxeles.

![example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)



### Creating tensors


Lo primero que vamos a crear es un **escalar**. Un escalar es un solo número y en términos de tensor es un tensor de dimensión cero.


In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)


Se imprimió el tensor(7)
Eso significa que aunque escalar es un solo número, es de tipo `torch.Tensor`.

Podemos verificar las dimensiones de un tensor usando el atributo ndim.

In [3]:
scalar.ndim

0

¿Y si quisiéramos recuperar el número del tensor?
Para hacerlo podemos usar el método item().

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7



Un **vector** es un tensor de una sola dimensión pero puede contener muchos números.

Por ejemplo, podrías tener un vector `[3, 2]` para describir `[dormitorios, baños]` en tu casa. O podría tener `[3, 2, 2]` para describir `[dormitorios, baños, aparcamientos]` en su casa.

La tendencia importante aquí es que un vector es flexible en lo que puede representar (lo mismo con los tensores).

In [5]:
# Vector
vector = torch.tensor([7, 3, 7])
vector

tensor([7, 3, 7])

¿Cuántas dimensiones crees que tendrá?

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

Otro concepto importante para los tensores es su atributo de `shape`.  

Te dice cómo están dispuestos los elementos dentro de ellos.

In [7]:
# Check shape of vector
vector.shape

torch.Size([3])

In [12]:
for i in vector:
  print(i)

tensor(7)
tensor(3)
tensor(7)


Let's now see a **matrix**.

In [13]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
# Check number of dimensions
MATRIX.ndim

2

In [15]:
# Check shape
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [20]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:

#[num series, longitud , features]


In [21]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]
                      ])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [23]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([4, 3, 3])

### Tensores Random

In essence:

`Empezar con número aleatorios -> mirar la data -> actualizar los números random -> mirar la data -> actualizar los números random...`


 * Initialization
 * Representation
 * Optimization


Por ahora, veamos cómo crear un tensor de números aleatorios [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html).


In [24]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.5630, 0.3598, 0.4676, 0.5206],
        [0.1535, 0.0688, 0.9549, 0.5311],
        [0.9572, 0.6075, 0.1558, 0.3164]])

La flexibilidad de `torch.rand()` es que podemos ajustar el `size` para que sea lo que queramos.

In [25]:
# Create a random tensor of size (4, 224, 3)
random_image_size_tensor = torch.rand(size=(4, 224, 3))

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([4, 224, 3]), 3)

In [26]:
random_image_size_tensor[0]

tensor([[0.9327, 0.3735, 0.6926],
        [0.3034, 0.3217, 0.9531],
        [0.5069, 0.3444, 0.2804],
        [0.1776, 0.9170, 0.8172],
        [0.5842, 0.1399, 0.0891],
        [0.8748, 0.4421, 0.5746],
        [0.8440, 0.0507, 0.4269],
        [0.7128, 0.4474, 0.5165],
        [0.4816, 0.0989, 0.5498],
        [0.2676, 0.7330, 0.6781],
        [0.0034, 0.3367, 0.2732],
        [0.1797, 0.5412, 0.1341],
        [0.4194, 0.5582, 0.9464],
        [0.9490, 0.9675, 0.6204],
        [0.5040, 0.5081, 0.4053],
        [0.9389, 0.7233, 0.7180],
        [0.0947, 0.8127, 0.6500],
        [0.7125, 0.5301, 0.5636],
        [0.2686, 0.4841, 0.9727],
        [0.7370, 0.2372, 0.9956],
        [0.1001, 0.7746, 0.6144],
        [0.7354, 0.1238, 0.3239],
        [0.5462, 0.6766, 0.7992],
        [0.6647, 0.5351, 0.6151],
        [0.6430, 0.2403, 0.4428],
        [0.8267, 0.3051, 0.8426],
        [0.4150, 0.6482, 0.6896],
        [0.7063, 0.3658, 0.4511],
        [0.4178, 0.6826, 0.1593],
        [0.218

### Zeros and ones

A veces solo querrás llenar los tensores con ceros o unos.

Vamos a crear un tensor lleno de ceros con [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html)


In [48]:
# Create a tensor of all zeros
zeros = torch.zeros(size=([1, 3, 10]))


tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

Podemos hacer lo mismo para crear un tensor de todos unos usando[`torch.ones()` ](https://pytorch.org/docs/stable/generated/torch.ones.html)

In [49]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range and tensors like
A veces, es posible que desee un rango de números, como del 1 al 10 o del 0 al 100.

Podemos usar `torch.arange(start, end, step)` para hacerlo.

Donde:
* `start` = Comienzo del range (e.g. 0)
* `end` = Fin del range (e.g. 10)
* `step` = Cuantos pasos entre cada valor (e.g. 1)


In [51]:

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:

# Create a range of values 0 to 20
zero_to_twenty = torch.arange(start=0, end=20, step=2)
zero_to_twenty

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

A veces, es posible que desee un tensor de cierto tipo con la misma forma que otro tensor.

Por ejemplo, un tensor de todos ceros con la misma forma que un tensor anterior.

Para hacerlo se puede usar [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) o [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html)

In [53]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Hay muchos diferentes [tipos de datos en PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types) de tensores disponibles.

El tipo más común (y generalmente el predeterminado) es `torch.float32` o `torch.float`.

Esto se conoce como "32-bit floating point".

Tambien hay 16-bit floating point (`torch.float16`) y 64-bit floating point (`torch.float64`).


In [54]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64, # defaults to None, which is torch.float32 or whatever datatype is passed
                               )
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float64, device(type='cpu'))

## Getting information from tensors

Una vez que haya creado tensores, es posible que desee obtener información de ellos.

Creemos un tensor aleatorio y descubramos detalles al respecto.

In [55]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7574, 0.3132, 0.9841, 0.4968],
        [0.6589, 0.0980, 0.5814, 0.9199],
        [0.9935, 0.9566, 0.3670, 0.9723]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensor operations)

En deep learning generalmente se manejan muchas operaciones con data (imagenes, texto, video, audio, estructuras, etc) que son respresentadas con tensores.

These operations are combinaciones between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


### Basic operations

Comencemos con algunas de las operaciones fundamentales, suma (`+`), resta (`-`), multiplicación (`*`).



In [35]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [39]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [40]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [41]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [42]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (is all you need)

Vamos a crear un tensor y realizar una multiplicación por elementos y una multiplicación de matrices en él.

In [43]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [44]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [45]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [56]:

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [57]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [58]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [59]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [51]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min, max, mean, sum, etc (aggregation)


Vamos a crear un tensor y luego encontrar el máximo, el mínimo, la media y la suma.





In [60]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [62]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [63]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Change tensor datatype

In [64]:
# Create a tensor and check its datatype
tensorr = torch.arange(10., 100., 10.)
tensorr.dtype

torch.float32

In [65]:
# Create a float16 tensor
tensor_float16 = tensorr.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

### Reshaping, stacking, squeezing and unsqueezing

In [66]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), 1)

Ahora agreguemos una dimensión extra con `torch.reshape()`.

In [68]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [72]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [73]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [74]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

In [75]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [84]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [85]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [86]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [87]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## PyTorch tensors & NumPy
Dado que NumPy es una popular biblioteca de computación numérica de Python, PyTorch tiene la funcionalidad para interactuar con ella muy bien.

Los dos métodos principales para usar NumPy a PyTorch (y viceversa) son:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

In [88]:

# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Reproducibility




``start with random numbers -> tensor operations -> try to make better (again and again and again)``



In [94]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
print(random_tensor_A <= random_tensor_B)
print(torch.equal(random_tensor_A, random_tensor_B))

Tensor A:
tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])

Tensor B:
tensor([[0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447]])

Does Tensor A equal Tensor B? (anywhere)
tensor([[ True,  True,  True, False],
        [ True, False,  True,  True],
        [ True, False,  True,  True]])
False


In [92]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### 1. Getting a GPU

In [1]:
!nvidia-smi

Tue Sep 26 16:03:07 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [3]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

In [6]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [10]:
tensor_on_gpu.cpu().numpy()

numpy.ndarray

## Exercises

All of the exercises are focused on practicing the code above.

You should be able to complete them by referencing each section or by following the resource(s) linked.

**Resources:**

* [Exercise template notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb).
* [Example solutions notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb) (try the exercises *before* looking at this).

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).
2. Create a random tensor with shape `(7, 7)`.
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).
4. Set the random seed to `0` and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.
6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.